using System.Globalization;

namespace FlightScanner.Features.Localization;

public static class UiText
{
    private static readonly Dictionary<string, Dictionary<string, string>> Values = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Account"] = "Account",
            ["Dashboard"] = "Dashboard",
            ["Search"] = "Search",
            ["Alerts"] = "Alerts",
            ["Users"] = "Users",
            ["Reminders"] = "Reminders",
            ["FlightApi"] = "Flight API",
            ["Register"] = "Register",
            ["Login"] = "Login",
            ["Logout"] = "Logout",
            ["Language"] = "Language",
            ["Continent"] = "Continent",
            ["Country"] = "Country",
            ["Return"] = "Return",
            ["From"] = "From",
            ["To"] = "To",
            ["ToLower"] = "to",
            ["Depart"] = "Depart",
            ["CountryCityAirport"] = "Country, city or airport",
            ["TravellersCabin"] = "Travellers and cabin class",
            ["CabinClass"] = "Cabin class",
            ["Adults"] = "Adults",
            ["Children"] = "Children",
            ["Aged18"] = "Aged 18+",
            ["Aged0To17"] = "Aged 0 to 17",
            ["Apply"] = "Apply",
            ["AddNearbyAirports"] = "Add nearby airports",
            ["DirectFlights"] = "Direct flights",
            ["Currency"] = "Currency",
            ["MaxStops"] = "Max stops",
            ["CheckedBags"] = "Checked bags",
            ["AlertTarget"] = "Alert target",
            ["SaveAlert"] = "Save alert",
            ["FareResults"] = "Fare results",
            ["OffersFound"] = "{0} offers found for {1} to {2}.",
            ["Stop"] = "stop",
            ["Stops"] = "stops",
            ["Open"] = "Open",
            ["AirlineDirectSearch"] = "Airline direct search",
            ["AirlineDirectSubtitle"] = "Regular and low-cost airline booking pages for this route.",
            ["SearchAirline"] = "Search airline",
            ["Traveller"] = "traveller",
            ["Travellers"] = "travellers",
            ["NoLiveProvider"] = "No live provider fares returned. Add Amadeus credentials under Admin > Flight API, or use the airline-direct links below.",
            ["LoginExpired"] = "Login expired. Please sign in again.",
            ["AlertSaved"] = "Alert saved. The background scanner will check it automatically.",
            ["DepartDateInvalid"] = "Enter a depart date as dd/mm/yyyy.",
            ["ReturnDateInvalid"] = "Enter a return date as dd/mm/yyyy.",
            ["DepartDatePast"] = "Depart date cannot be earlier than today.",
            ["ReturnDatePast"] = "Return date cannot be earlier than today.",
            ["DurationUnavailable"] = "duration unavailable",
            ["Economy"] = "Economy",
            ["PremiumEconomy"] = "Premium economy",
            ["Business"] = "Business",
            ["First"] = "First"
        },
        ["fr"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Account"] = "Compte",
            ["Dashboard"] = "Tableau de bord",
            ["Search"] = "Rechercher",
            ["Alerts"] = "Alertes",
            ["Users"] = "Utilisateurs",
            ["Reminders"] = "Rappels",
            ["FlightApi"] = "API vols",
            ["Register"] = "Inscription",
            ["Login"] = "Connexion",
            ["Logout"] = "Déconnexion",
            ["Language"] = "Langue",
            ["Continent"] = "Continent",
            ["Country"] = "Pays",
            ["Return"] = "Aller-retour",
            ["From"] = "Départ",
            ["To"] = "Arrivée",
            ["ToLower"] = "vers",
            ["Depart"] = "Départ",
            ["CountryCityAirport"] = "Pays, ville ou aéroport",
            ["TravellersCabin"] = "Voyageurs et cabine",
            ["CabinClass"] = "Classe cabine",
            ["Adults"] = "Adultes",
            ["Children"] = "Enfants",
            ["Aged18"] = "18 ans et plus",
            ["Aged0To17"] = "De 0 à 17 ans",
            ["Apply"] = "Appliquer",
            ["AddNearbyAirports"] = "Ajouter les aéroports proches",
            ["DirectFlights"] = "Vols directs",
            ["Currency"] = "Devise",
            ["MaxStops"] = "Escales max",
            ["CheckedBags"] = "Bagages",
            ["AlertTarget"] = "Prix cible",
            ["SaveAlert"] = "Enregistrer l’alerte",
            ["FareResults"] = "Résultats",
            ["OffersFound"] = "{0} offres trouvées de {1} à {2}.",
            ["Stop"] = "escale",
            ["Stops"] = "escales",
            ["Open"] = "Ouvrir",
            ["AirlineDirectSearch"] = "Recherche directe compagnies",
            ["AirlineDirectSubtitle"] = "Pages de réservation des compagnies classiques et low-cost pour cet itinéraire.",
            ["SearchAirline"] = "Chercher",
            ["Traveller"] = "voyageur",
            ["Travellers"] = "voyageurs",
            ["NoLiveProvider"] = "Aucune offre live retournée. Ajoutez vos identifiants Amadeus dans Admin > API vols, ou utilisez les liens directs des compagnies ci-dessous.",
            ["LoginExpired"] = "Session expirée. Veuillez vous reconnecter.",
            ["AlertSaved"] = "Alerte enregistrée. Le scanner la vérifiera automatiquement.",
            ["DepartDateInvalid"] = "Entrez une date de départ au format jj/mm/aaaa.",
            ["ReturnDateInvalid"] = "Entrez une date de retour au format jj/mm/aaaa.",
            ["DepartDatePast"] = "La date de départ ne peut pas être antérieure à aujourd’hui.",
            ["ReturnDatePast"] = "La date de retour ne peut pas être antérieure à aujourd’hui.",
            ["DurationUnavailable"] = "durée indisponible",
            ["Economy"] = "Économie",
            ["PremiumEconomy"] = "Premium economy",
            ["Business"] = "Affaires",
            ["First"] = "Première"
        },
        ["ar"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Account"] = "الحساب",
            ["Dashboard"] = "لوحة التحكم",
            ["Search"] = "البحث",
            ["Alerts"] = "التنبيهات",
            ["Users"] = "المستخدمون",
            ["Reminders"] = "التذكيرات",
            ["FlightApi"] = "واجهة الرحلات",
            ["Register"] = "تسجيل",
            ["Login"] = "دخول",
            ["Logout"] = "خروج",
            ["Language"] = "اللغة",
            ["Continent"] = "قارة",
            ["Country"] = "دولة",
            ["Return"] = "ذهاب وعودة",
            ["From"] = "من",
            ["To"] = "إلى",
            ["ToLower"] = "إلى",
            ["Depart"] = "المغادرة",
            ["CountryCityAirport"] = "دولة أو مدينة أو مطار",
            ["TravellersCabin"] = "المسافرون ودرجة السفر",
            ["CabinClass"] = "درجة السفر",
            ["Adults"] = "البالغون",
            ["Children"] = "الأطفال",
            ["Aged18"] = "18 سنة فأكثر",
            ["Aged0To17"] = "من 0 إلى 17 سنة",
            ["Apply"] = "تطبيق",
            ["AddNearbyAirports"] = "إضافة المطارات القريبة",
            ["DirectFlights"] = "رحلات مباشرة",
            ["Currency"] = "العملة",
            ["MaxStops"] = "أقصى توقفات",
            ["CheckedBags"] = "الأمتعة",
            ["AlertTarget"] = "سعر التنبيه",
            ["SaveAlert"] = "حفظ التنبيه",
            ["FareResults"] = "نتائج الأسعار",
            ["OffersFound"] = "تم العثور على {0} عروض من {1} إلى {2}.",
            ["Stop"] = "توقف",
            ["Stops"] = "توقفات",
            ["Open"] = "فتح",
            ["AirlineDirectSearch"] = "بحث مباشر لدى شركات الطيران",
            ["AirlineDirectSubtitle"] = "صفحات حجز شركات الطيران العادية ومنخفضة التكلفة لهذا المسار.",
            ["SearchAirline"] = "بحث الشركة",
            ["Traveller"] = "مسافر",
            ["Travellers"] = "مسافرون",
            ["NoLiveProvider"] = "لم ترجع عروض مباشرة. أضف بيانات Amadeus من لوحة الإدارة > واجهة الرحلات، أو استخدم روابط شركات الطيران أدناه.",
            ["LoginExpired"] = "انتهت الجلسة. يرجى تسجيل الدخول مرة أخرى.",
            ["AlertSaved"] = "تم حفظ التنبيه. سيقوم الماسح بفحصه تلقائياً.",
            ["DepartDateInvalid"] = "أدخل تاريخ المغادرة بصيغة dd/mm/yyyy.",
            ["ReturnDateInvalid"] = "أدخل تاريخ العودة بصيغة dd/mm/yyyy.",
            ["DepartDatePast"] = "لا يمكن أن يكون تاريخ المغادرة قبل اليوم.",
            ["ReturnDatePast"] = "لا يمكن أن يكون تاريخ العودة قبل اليوم.",
            ["DurationUnavailable"] = "المدة غير متوفرة",
            ["Economy"] = "اقتصادية",
            ["PremiumEconomy"] = "اقتصادية مميزة",
            ["Business"] = "أعمال",
            ["First"] = "الأولى"
        }
    };

    public static string T(string key)
    {
        var culture = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        if (Values.TryGetValue(culture, out var localized) && localized.TryGetValue(key, out var value))
        {
            return value;
        }

        return Values["en"].TryGetValue(key, out var fallback) ? fallback : key;
    }
}
